// Auto-generated legacy user seed data (profiles + special roles) for account recovery.
export type LegacyProfile = {
  email: string; full_name: string; phone: string; discord_username: string;
  country: string; gang_name: string; gang_type: string; token_balance: number;
  ingame_name: string; xp: number; vip_tier: string;
};
export const LEGACY_PROFILES: LegacyProfile[] = [
{
"email": "davismichael0055@gmail.com",
"full_name": "Davis Michael",
"phone": "0812050551",
"discord_username": "lomitashootersleagu",
"country": "",
"gang_name": "H",
"gang_type": "F",
"token_balance": 0,
"ingame_name": "Davis Michael",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "sopyjaja16@gmail.com",
"full_name": "Riala",
"phone": "",
"discord_username": "",
"country": "",
"gang_name": "Terrorist",
"gang_type": "",
"token_balance": 9000000,
"ingame_name": "",
"xp": 200,
"vip_tier": "bronze"
},
{
"email": "damilarejaiyeoba4@gmail.com",
"full_name": "Dreson",
"phone": "07066625595",
"discord_username": "dreson_fbi",
"country": "Nigeria",
"gang_name": "Risotto",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Dreson risotto",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "rayburnkhalz@gmail.com",
"full_name": "Biggest Ray",
"phone": "07038161269",
"discord_username": "Blkray",
"country": "Nigeria",
"gang_name": "Silent killers",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Biggest Ray",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "efosaatujohnon@gmail.com",
"full_name": "David Johnson",
"phone": "",
"discord_username": "Mr Gold",
"country": "Nigeria",
"gang_name": "RRR",
"gang_type": "G",
"token_balance": 3000000,
"ingame_name": "Mr Gold",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "lyrician30d@gmail.com",
"full_name": "Mr Dealer",
"phone": "08138102407",
"discord_username": "mr.dealer1",
"country": "Nigeria",
"gang_name": "Mosthated",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Mr Dealer",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "adamayobami081@gmail.com",
"full_name": "TripleAAA",
"phone": "08072823728",
"discord_username": "triple_.aaa",
"country": "Nigeria",
"gang_name": "Nill",
"gang_type": "G",
"token_balance": 500000,
"ingame_name": "Triple Aaa",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "dfwpain286@gmail.com",
"full_name": "Nerfed wenski",
"phone": "",
"discord_username": "19swacko",
"country": "Psychhhh",
"gang_name": "Terrorist squad",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "adeyemiadeife83@gmail.com",
"full_name": "Fw Slick",
"phone": "08135604963",
"discord_username": "apa_ni_",
"country": "Nigeria",
"gang_name": "Trouble Gang",
"gang_type": "G",
"token_balance": 500000,
"ingame_name": "Fw Slick",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "dagoldsmithval@gmail.com",
"full_name": "Starboy Smith",
"phone": "09034795211",
"discord_username": "praizparis_50751",
"country": "Nigeria",
"gang_name": "Free Civilian",
"gang_type": "F",
"token_balance": 500000,
"ingame_name": "Starboy Smith",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "kendalll.trucking89@gmail.com",
"full_name": "Popman Makaveli",
"phone": "+27663162141",
"discord_username": "cptkohl",
"country": "South Africa",
"gang_name": "Trouble gang1",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Popman Makaveli",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "ayomideayinuola87@gmail.com",
"full_name": "Haywhy",
"phone": "09064409764",
"discord_username": "@dfghaywhy",
"country": "Nigeria",
"gang_name": "",
"gang_type": "",
"token_balance": 500000,
"ingame_name": "",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "shagyman47@gmail.com",
"full_name": "Burti",
"phone": "",
"discord_username": "19swacko",
"country": "",
"gang_name": "Onyabo",
"gang_type": "F",
"token_balance": 500100,
"ingame_name": "Burti vybes",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "bidfind31@gmail.com",
"full_name": "Alhaji sanu",
"phone": "",
"discord_username": "dweylomo",
"country": "Nigeria",
"gang_name": "Alhaji sanu",
"gang_type": "F",
"token_balance": 500000,
"ingame_name": "Alhaji sanu",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "anjeremy7017@gmail.com",
"full_name": "Caputooo",
"phone": "0703 342 7586",
"discord_username": "Caputoo",
"country": "Nigeria",
"gang_name": "Caputooo",
"gang_type": "G",
"token_balance": 500000,
"ingame_name": "",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "ojediransodiq86@gmail.com",
"full_name": "Tag lm",
"phone": "08051696271",
"discord_username": "taglm0806",
"country": "Nigeria",
"gang_name": "Lagos Mafia",
"gang_type": "G",
"token_balance": 500000,
"ingame_name": "",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "chinemeremfavour2023@gmail.com",
"full_name": "Rebel",
"phone": "09044258816",
"discord_username": "Rebelisguilty",
"country": "Nigeria",
"gang_name": "Presidential",
"gang_type": "G",
"token_balance": 10000000,
"ingame_name": "Big explorer",
"xp": 50,
"vip_tier": "bronze"
},
{
"email": "ayclassicpro@gmail.com",
"full_name": "Adepoju Ayomide",
"phone": "08164150967",
"discord_username": "Ayclassic",
"country": "Nigeria",
"gang_name": "Goshen",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Mr Ayclassic",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "pappiechi047@gmail.com",
"full_name": "Joker",
"phone": "08169965725",
"discord_username": "j0k3r0171",
"country": "Nigeria",
"gang_name": "Risotto",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Joker Risotto",
"xp": 50,
"vip_tier": "bronze"
},
{
"email": "promisejames545@gmail.com",
"full_name": "Fire",
"phone": "09015469737",
"discord_username": "fire042539",
"country": "Nigeria",
"gang_name": "",
"gang_type": "",
"token_balance": 1399999,
"ingame_name": "",
"xp": 165,
"vip_tier": "bronze"
},
{
"email": "daddy1yo2@gmail.com",
"full_name": "Avaia pierce",
"phone": "+447598798701",
"discord_username": "Little baby",
"country": "United Kingdom",
"gang_name": "Avaia pierce",
"gang_type": "G",
"token_balance": 18899999,
"ingame_name": "Avaia pierce",
"xp": 115,
"vip_tier": "bronze"
},
{
"email": "yunggee190@gmail.com",
"full_name": "Nerfed Yenski",
"phone": "",
"discord_username": "ancestoryg",
"country": "United Kingdom",
"gang_name": "terrorist squad",
"gang_type": "G",
"token_balance": 5110000,
"ingame_name": "",
"xp": 50,
"vip_tier": "bronze"
},
{
"email": "asomahy05@gmail.com",
"full_name": "Mr summer",
"phone": "0594908477",
"discord_username": "Jr shaker",
"country": "Ghana",
"gang_name": "Presidential",
"gang_type": "G",
"token_balance": 500000,
"ingame_name": "",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "princejehu12345@gmail.com",
"full_name": "Gustavo Pounds",
"phone": "+233535994882",
"discord_username": "Unknownmf004",
"country": "Ghana",
"gang_name": "TROUBLE GANG",
"gang_type": "G",
"token_balance": 500000,
"ingame_name": "Kael Santiago",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "samueloluwapelumi901@gmail.com",
"full_name": "Samuel Oluwapelumi",
"phone": "8110953906",
"discord_username": "Sammy Yagii",
"country": "Nigeria",
"gang_name": "Army",
"gang_type": "F",
"token_balance": 0,
"ingame_name": "Sammy Yagii",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "copperkevin121@gmail.com",
"full_name": "Ola",
"phone": "8106168636",
"discord_username": "Olaseni777",
"country": "Nigeria",
"gang_name": "Money Mafia",
"gang_type": "G",
"token_balance": 500000,
"ingame_name": "Prestige papi",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "paulamber054@gmail.com",
"full_name": "Drizzy brady",
"phone": "2402535961",
"discord_username": "",
"country": "USA",
"gang_name": "Flyest",
"gang_type": "G",
"token_balance": 11400000,
"ingame_name": "",
"xp": 35165,
"vip_tier": "legend"
},
{
"email": "fawazagbeniyi4@gmail.com",
"full_name": "Thugwannabe",
"phone": "07063706300",
"discord_username": "Baby2x",
"country": "Nigeria",
"gang_name": "Trouble gang",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Laka nohope",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "sarahsmi100@gmail.com",
"full_name": "Lil Davee",
"phone": "9023031869",
"discord_username": "Davedc001",
"country": "Nigeria",
"gang_name": "Trouble gang2",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Lil Davee",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "lomitashootersleague@gmail.com",
"full_name": "\u01a4I\u01a6\u023a\u01acE",
"phone": "081234567890",
"discord_username": "@life_of_a_pirate",
"country": "PLUTO",
"gang_name": "SUPPORT TEAM",
"gang_type": "G",
"token_balance": 57005660,
"ingame_name": "",
"xp": 101205,
"vip_tier": "legend"
},
{
"email": "boasiwaju@gmail.com",
"full_name": "Ayo",
"phone": "09068712056",
"discord_username": "ayoxx031",
"country": "Nigeria",
"gang_name": "Terrorist Squad",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Nerfed Ayo",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "kiser9021@gmail.com",
"full_name": "Kvng cruze",
"phone": "+2349069640923",
"discord_username": "Kvngcruze",
"country": "Nigeria",
"gang_name": "Murder fcm",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Kvngcruze fcm",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "yungupdate419@gmail.com",
"full_name": "Yung Update",
"phone": "0535704414",
"discord_username": "Yungupdate_",
"country": "Ghana",
"gang_name": "Yung Update",
"gang_type": "F",
"token_balance": 0,
"ingame_name": "Yung Update",
"xp": 50,
"vip_tier": "bronze"
},
{
"email": "juwonfolorunsho01@gmail.com",
"full_name": "Mr jago",
"phone": "07061791988",
"discord_username": "Jago_is_bigg",
"country": "",
"gang_name": "Civilian",
"gang_type": "F",
"token_balance": 0,
"ingame_name": "Mr jago",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "beautymistress27@gmail.com",
"full_name": "Pappie",
"phone": "08169965725",
"discord_username": "j0k3r0171",
"country": "Nigeria",
"gang_name": "Risotto",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Pappie Joker",
"xp": 50,
"vip_tier": "bronze"
},
{
"email": "maverickrp521@gmail.com",
"full_name": "Mavvv",
"phone": "00000000000",
"discord_username": "Not Mav",
"country": "United Nigeria",
"gang_name": "OTA",
"gang_type": "G",
"token_balance": 120000,
"ingame_name": "OTA layzzzbelt",
"xp": 165,
"vip_tier": "bronze"
},
{
"email": "schoolboyyy0@gmail.com",
"full_name": "Levi",
"phone": "",
"discord_username": "Una question don dey to much",
"country": "Togo",
"gang_name": "Public menace",
"gang_type": "G",
"token_balance": 19125000,
"ingame_name": "Public menace",
"xp": 165,
"vip_tier": "bronze"
},
{
"email": "bigbayorvu123@gmail.com",
"full_name": "Bayor",
"phone": "23407017702095",
"discord_username": "bby4020t",
"country": "Nigeria",
"gang_name": "Opium",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Bigbayor",
"xp": 115,
"vip_tier": "bronze"
},
{
"email": "michaelvictor0014@gmail.com",
"full_name": "TEST ACCOUNT",
"phone": "",
"discord_username": "",
"country": "",
"gang_name": "",
"gang_type": "",
"token_balance": 1951100,
"ingame_name": "",
"xp": 0,
"vip_tier": "bronze"
},
{
"email": "ohkyes11@gmail.com",
"full_name": "Taylor Lm",
"phone": "",
"discord_username": "@brodasmart",
"country": "Nigeria",
"gang_name": "LAGOS MAFIA",
"gang_type": "G",
"token_balance": 2000000,
"ingame_name": "",
"xp": 100,
"vip_tier": "bronze"
},
{
"email": "asomahjames86@gmail.com",
"full_name": "Asomah Caleb",
"phone": "0594908477",
"discord_username": "Jr shaker",
"country": "Ghana",
"gang_name": "Presidential",
"gang_type": "G",
"token_balance": 0,
"ingame_name": "Mr summer",
"xp": 115,
"vip_tier": "bronze"
},
{
"email": "stacey4000f@gmail.com",
"full_name": "Oba",
"phone": "08111619313",
"discord_username": "Ajibola1470",
"country": "Nigeria",
"gang_name": "Lagos mafia",
"gang_type": "G",
"token_balance": 500,
"ingame_name": "Why Meech",
"xp": 50,
"vip_tier": "bronze"
},
{
"email": "worldpresidentowoniboyz@gmail.com",
"full_name": "Verified Finn",
"phone": "+353 89 228 7782",
"discord_username": "Money_bagg_",
"country": "Ireland",
"gang_name": "Murder fcm",
"gang_type": "G",
"token_balance": 3729999,
"ingame_name": "",
"xp": 265,
"vip_tier": "bronze"
},
{
"email": "adexliade@gmail.com",
"full_name": "Biggest Adexxxx",
"phone": "4372452784",
"discord_username": "Rules99999",
"country": "Canada",
"gang_name": "Oyeku",
"gang_type": "G",
"token_balance": 10500000,
"ingame_name": "Biggest Adexxxx",
"xp": 515,
"vip_tier": "silver"
},
{
"email": "flexnikki54@gmail.com",
"full_name": "Nini Ola",
"phone": "9137735996",
"discord_username": "Silentghost2",
"country": "Nigeria",
"gang_name": "No gang",
"gang_type": "G",
"token_balance": 6369999,
"ingame_name": "Nini Ola",
"xp": 165,
"vip_tier": "bronze"
},
{
"email": "hamzatadetunji4@gmail.com",
"full_name": "Edward ola",
"phone": "07049426788",
"discord_username": "Edwardola",
"country": "Nigeria",
"gang_name": "",
"gang_type": "",
"token_balance": 10110002,
"ingame_name": "Edward ola",
"xp": 215,
"vip_tier": "bronze"
},
{
"email": "kellyjameskj0@gmail.com",
"full_name": "Tom tom",
"phone": "09078533747",
"discord_username": "anthonyelvis",
"country": "Nig",
"gang_name": "Oyeku",
"gang_type": "G",
"token_balance": 1408749,
"ingame_name": "Tom tomm",
"xp": 115,
"vip_tier": "bronze"
},
{
"email": "nimasjunior11@gmail.com",
"full_name": "Little baby",
"phone": "+447598798701",
"discord_username": "Njj_1",
"country": "United Kingdom",
"gang_name": "Terrorist Squad",
"gang_type": "G",
"token_balance": 49849999,
"ingame_name": "",
"xp": 315,
"vip_tier": "bronze"
},
{
"email": "emmanuelolowookere959@gmail.com",
"full_name": "Syn Xx",
"phone": "08160164804",
"discord_username": "mr_bob_73",
"country": "Nigeria",
"gang_name": "Trouble gang",
"gang_type": "G",
"token_balance": 110000,
"ingame_name": "Syn Xx",
"xp": 100,
"vip_tier": "bronze"
}
];
export const LEGACY_ROLES: { email: string; role: string }[] = [{"email": "ohkyes11@gmail.com", "role": "admin"}, {"email": "lomitashootersleague@gmail.com", "role": "admin"}, {"email": "michaelvictor0014@gmail.com", "role": "moderator"}, {"email": "dfwpain286@gmail.com", "role": "admin"}, {"email": "yunggee190@gmail.com", "role": "admin"}, {"email": "paulamber054@gmail.com", "role": "admin"}, {"email": "sopyjaja16@gmail.com", "role": "admin"}, {"email": "juwonfolorunsho01@gmail.com", "role": "admin"}];
