/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as VirtualRouteImport } from './routes/virtual'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GangsRouteImport } from './routes/gangs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VirtualHistoryRouteImport } from './routes/virtual.history'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as ApiPublicVirtualTickRouteImport } from './routes/api/public/virtual-tick'
import { Route as ApiPublicHooksSendPushRouteImport } from './routes/api/public/hooks/send-push'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualRoute = VirtualRouteImport.update({
  id: '/virtual',
  path: '/virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GangsRoute = GangsRouteImport.update({
  id: '/gangs',
  path: '/gangs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualHistoryRoute = VirtualHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => VirtualRoute,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const ApiPublicVirtualTickRoute = ApiPublicVirtualTickRouteImport.update({
  id: '/api/public/virtual-tick',
  path: '/api/public/virtual-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendPushRoute = ApiPublicHooksSendPushRouteImport.update({
  id: '/api/public/hooks/send-push',
  path: '/api/public/hooks/send-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/virtual': typeof VirtualRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/virtual/history': typeof VirtualHistoryRoute
  '/api/public/virtual-tick': typeof ApiPublicVirtualTickRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/virtual': typeof VirtualRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/virtual/history': typeof VirtualHistoryRoute
  '/api/public/virtual-tick': typeof ApiPublicVirtualTickRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/virtual': typeof VirtualRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/virtual/history': typeof VirtualHistoryRoute
  '/api/public/virtual-tick': typeof ApiPublicVirtualTickRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/chat'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/tasks'
    | '/virtual'
    | '/watchlist'
    | '/withdraw'
    | '/matches/$matchId'
    | '/ticket/$id'
    | '/virtual/history'
    | '/api/public/virtual-tick'
    | '/api/public/hooks/send-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/chat'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/tasks'
    | '/virtual'
    | '/watchlist'
    | '/withdraw'
    | '/matches/$matchId'
    | '/ticket/$id'
    | '/virtual/history'
    | '/api/public/virtual-tick'
    | '/api/public/hooks/send-push'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/chat'
    | '/checkout'
    | '/dashboard'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/support'
    | '/tasks'
    | '/virtual'
    | '/watchlist'
    | '/withdraw'
    | '/matches/$matchId'
    | '/ticket/$id'
    | '/virtual/history'
    | '/api/public/virtual-tick'
    | '/api/public/hooks/send-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GangsRoute: typeof GangsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TasksRoute: typeof TasksRoute
  VirtualRoute: typeof VirtualRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  WithdrawRoute: typeof WithdrawRoute
  TicketIdRoute: typeof TicketIdRoute
  ApiPublicVirtualTickRoute: typeof ApiPublicVirtualTickRoute
  ApiPublicHooksSendPushRoute: typeof ApiPublicHooksSendPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual': {
      id: '/virtual'
      path: '/virtual'
      fullPath: '/virtual'
      preLoaderRoute: typeof VirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gangs': {
      id: '/gangs'
      path: '/gangs'
      fullPath: '/gangs'
      preLoaderRoute: typeof GangsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual/history': {
      id: '/virtual/history'
      path: '/history'
      fullPath: '/virtual/history'
      preLoaderRoute: typeof VirtualHistoryRouteImport
      parentRoute: typeof VirtualRoute
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/api/public/virtual-tick': {
      id: '/api/public/virtual-tick'
      path: '/api/public/virtual-tick'
      fullPath: '/api/public/virtual-tick'
      preLoaderRoute: typeof ApiPublicVirtualTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-push': {
      id: '/api/public/hooks/send-push'
      path: '/api/public/hooks/send-push'
      fullPath: '/api/public/hooks/send-push'
      preLoaderRoute: typeof ApiPublicHooksSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface VirtualRouteChildren {
  VirtualHistoryRoute: typeof VirtualHistoryRoute
}

const VirtualRouteChildren: VirtualRouteChildren = {
  VirtualHistoryRoute: VirtualHistoryRoute,
}

const VirtualRouteWithChildren =
  VirtualRoute._addFileChildren(VirtualRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GangsRoute: GangsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TasksRoute: TasksRoute,
  VirtualRoute: VirtualRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  WithdrawRoute: WithdrawRoute,
  TicketIdRoute: TicketIdRoute,
  ApiPublicVirtualTickRoute: ApiPublicVirtualTickRoute,
  ApiPublicHooksSendPushRoute: ApiPublicHooksSendPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
