/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as VirtualRouteImport } from './routes/virtual'
import { Route as TriviaRouteImport } from './routes/trivia'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PollsRouteImport } from './routes/polls'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModRouteImport } from './routes/mod'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LotteryRouteImport } from './routes/lottery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GangsRouteImport } from './routes/gangs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BetHistoryRouteImport } from './routes/bet-history'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VirtualInstantRouteImport } from './routes/virtual.instant'
import { Route as VirtualHistoryRouteImport } from './routes/virtual.history'
import { Route as VirtualChampionshipRouteImport } from './routes/virtual.championship'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as ApiPublicVirtualTickRouteImport } from './routes/api/public/virtual-tick'
import { Route as ApiPublicHooksSendPushRouteImport } from './routes/api/public/hooks/send-push'
import { Route as ApiPublicHooksProcessScheduledPushRouteImport } from './routes/api/public/hooks/process-scheduled-push'
import { Route as ApiPublicHooksBroadcastPushRouteImport } from './routes/api/public/hooks/broadcast-push'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualRoute = VirtualRouteImport.update({
  id: '/virtual',
  path: '/virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const TriviaRoute = TriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsRoute = PollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModRoute = ModRouteImport.update({
  id: '/mod',
  path: '/mod',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LotteryRoute = LotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GangsRoute = GangsRouteImport.update({
  id: '/gangs',
  path: '/gangs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BetHistoryRoute = BetHistoryRouteImport.update({
  id: '/bet-history',
  path: '/bet-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualInstantRoute = VirtualInstantRouteImport.update({
  id: '/instant',
  path: '/instant',
  getParentRoute: () => VirtualRoute,
} as any)
const VirtualHistoryRoute = VirtualHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => VirtualRoute,
} as any)
const VirtualChampionshipRoute = VirtualChampionshipRouteImport.update({
  id: '/championship',
  path: '/championship',
  getParentRoute: () => VirtualRoute,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const ApiPublicVirtualTickRoute = ApiPublicVirtualTickRouteImport.update({
  id: '/api/public/virtual-tick',
  path: '/api/public/virtual-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendPushRoute = ApiPublicHooksSendPushRouteImport.update({
  id: '/api/public/hooks/send-push',
  path: '/api/public/hooks/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessScheduledPushRoute =
  ApiPublicHooksProcessScheduledPushRouteImport.update({
    id: '/api/public/hooks/process-scheduled-push',
    path: '/api/public/hooks/process-scheduled-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBroadcastPushRoute =
  ApiPublicHooksBroadcastPushRouteImport.update({
    id: '/api/public/hooks/broadcast-push',
    path: '/api/public/hooks/broadcast-push',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/bet-history': typeof BetHistoryRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/lottery': typeof LotteryRoute
  '/matches': typeof MatchesRouteWithChildren
  '/mod': typeof ModRoute
  '/notifications': typeof NotificationsRoute
  '/polls': typeof PollsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/tournament': typeof TournamentRoute
  '/transactions': typeof TransactionsRoute
  '/trivia': typeof TriviaRoute
  '/virtual': typeof VirtualRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/virtual/championship': typeof VirtualChampionshipRoute
  '/virtual/history': typeof VirtualHistoryRoute
  '/virtual/instant': typeof VirtualInstantRoute
  '/api/public/virtual-tick': typeof ApiPublicVirtualTickRoute
  '/api/public/hooks/broadcast-push': typeof ApiPublicHooksBroadcastPushRoute
  '/api/public/hooks/process-scheduled-push': typeof ApiPublicHooksProcessScheduledPushRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/bet-history': typeof BetHistoryRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/lottery': typeof LotteryRoute
  '/matches': typeof MatchesRouteWithChildren
  '/mod': typeof ModRoute
  '/notifications': typeof NotificationsRoute
  '/polls': typeof PollsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/tournament': typeof TournamentRoute
  '/transactions': typeof TransactionsRoute
  '/trivia': typeof TriviaRoute
  '/virtual': typeof VirtualRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/virtual/championship': typeof VirtualChampionshipRoute
  '/virtual/history': typeof VirtualHistoryRoute
  '/virtual/instant': typeof VirtualInstantRoute
  '/api/public/virtual-tick': typeof ApiPublicVirtualTickRoute
  '/api/public/hooks/broadcast-push': typeof ApiPublicHooksBroadcastPushRoute
  '/api/public/hooks/process-scheduled-push': typeof ApiPublicHooksProcessScheduledPushRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/bet-history': typeof BetHistoryRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gangs': typeof GangsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/lottery': typeof LotteryRoute
  '/matches': typeof MatchesRouteWithChildren
  '/mod': typeof ModRoute
  '/notifications': typeof NotificationsRoute
  '/polls': typeof PollsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/surveys': typeof SurveysRoute
  '/tasks': typeof TasksRoute
  '/tournament': typeof TournamentRoute
  '/transactions': typeof TransactionsRoute
  '/trivia': typeof TriviaRoute
  '/virtual': typeof VirtualRouteWithChildren
  '/watchlist': typeof WatchlistRoute
  '/withdraw': typeof WithdrawRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/ticket/$id': typeof TicketIdRoute
  '/virtual/championship': typeof VirtualChampionshipRoute
  '/virtual/history': typeof VirtualHistoryRoute
  '/virtual/instant': typeof VirtualInstantRoute
  '/api/public/virtual-tick': typeof ApiPublicVirtualTickRoute
  '/api/public/hooks/broadcast-push': typeof ApiPublicHooksBroadcastPushRoute
  '/api/public/hooks/process-scheduled-push': typeof ApiPublicHooksProcessScheduledPushRoute
  '/api/public/hooks/send-push': typeof ApiPublicHooksSendPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/arcade'
    | '/bet-history'
    | '/chat'
    | '/checkout'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/lottery'
    | '/matches'
    | '/mod'
    | '/notifications'
    | '/polls'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/surveys'
    | '/tasks'
    | '/tournament'
    | '/transactions'
    | '/trivia'
    | '/virtual'
    | '/watchlist'
    | '/withdraw'
    | '/matches/$matchId'
    | '/ticket/$id'
    | '/virtual/championship'
    | '/virtual/history'
    | '/virtual/instant'
    | '/api/public/virtual-tick'
    | '/api/public/hooks/broadcast-push'
    | '/api/public/hooks/process-scheduled-push'
    | '/api/public/hooks/send-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/arcade'
    | '/bet-history'
    | '/chat'
    | '/checkout'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/lottery'
    | '/matches'
    | '/mod'
    | '/notifications'
    | '/polls'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/surveys'
    | '/tasks'
    | '/tournament'
    | '/transactions'
    | '/trivia'
    | '/virtual'
    | '/watchlist'
    | '/withdraw'
    | '/matches/$matchId'
    | '/ticket/$id'
    | '/virtual/championship'
    | '/virtual/history'
    | '/virtual/instant'
    | '/api/public/virtual-tick'
    | '/api/public/hooks/broadcast-push'
    | '/api/public/hooks/process-scheduled-push'
    | '/api/public/hooks/send-push'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/arcade'
    | '/bet-history'
    | '/chat'
    | '/checkout'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/gangs'
    | '/leaderboard'
    | '/login'
    | '/lottery'
    | '/matches'
    | '/mod'
    | '/notifications'
    | '/polls'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/sitemap.xml'
    | '/support'
    | '/surveys'
    | '/tasks'
    | '/tournament'
    | '/transactions'
    | '/trivia'
    | '/virtual'
    | '/watchlist'
    | '/withdraw'
    | '/matches/$matchId'
    | '/ticket/$id'
    | '/virtual/championship'
    | '/virtual/history'
    | '/virtual/instant'
    | '/api/public/virtual-tick'
    | '/api/public/hooks/broadcast-push'
    | '/api/public/hooks/process-scheduled-push'
    | '/api/public/hooks/send-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  ArcadeRoute: typeof ArcadeRoute
  BetHistoryRoute: typeof BetHistoryRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GangsRoute: typeof GangsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  LotteryRoute: typeof LotteryRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  ModRoute: typeof ModRoute
  NotificationsRoute: typeof NotificationsRoute
  PollsRoute: typeof PollsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  SurveysRoute: typeof SurveysRoute
  TasksRoute: typeof TasksRoute
  TournamentRoute: typeof TournamentRoute
  TransactionsRoute: typeof TransactionsRoute
  TriviaRoute: typeof TriviaRoute
  VirtualRoute: typeof VirtualRouteWithChildren
  WatchlistRoute: typeof WatchlistRoute
  WithdrawRoute: typeof WithdrawRoute
  TicketIdRoute: typeof TicketIdRoute
  ApiPublicVirtualTickRoute: typeof ApiPublicVirtualTickRoute
  ApiPublicHooksBroadcastPushRoute: typeof ApiPublicHooksBroadcastPushRoute
  ApiPublicHooksProcessScheduledPushRoute: typeof ApiPublicHooksProcessScheduledPushRoute
  ApiPublicHooksSendPushRoute: typeof ApiPublicHooksSendPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual': {
      id: '/virtual'
      path: '/virtual'
      fullPath: '/virtual'
      preLoaderRoute: typeof VirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trivia': {
      id: '/trivia'
      path: '/trivia'
      fullPath: '/trivia'
      preLoaderRoute: typeof TriviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls': {
      id: '/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof PollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod': {
      id: '/mod'
      path: '/mod'
      fullPath: '/mod'
      preLoaderRoute: typeof ModRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lottery': {
      id: '/lottery'
      path: '/lottery'
      fullPath: '/lottery'
      preLoaderRoute: typeof LotteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gangs': {
      id: '/gangs'
      path: '/gangs'
      fullPath: '/gangs'
      preLoaderRoute: typeof GangsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bet-history': {
      id: '/bet-history'
      path: '/bet-history'
      fullPath: '/bet-history'
      preLoaderRoute: typeof BetHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual/instant': {
      id: '/virtual/instant'
      path: '/instant'
      fullPath: '/virtual/instant'
      preLoaderRoute: typeof VirtualInstantRouteImport
      parentRoute: typeof VirtualRoute
    }
    '/virtual/history': {
      id: '/virtual/history'
      path: '/history'
      fullPath: '/virtual/history'
      preLoaderRoute: typeof VirtualHistoryRouteImport
      parentRoute: typeof VirtualRoute
    }
    '/virtual/championship': {
      id: '/virtual/championship'
      path: '/championship'
      fullPath: '/virtual/championship'
      preLoaderRoute: typeof VirtualChampionshipRouteImport
      parentRoute: typeof VirtualRoute
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/api/public/virtual-tick': {
      id: '/api/public/virtual-tick'
      path: '/api/public/virtual-tick'
      fullPath: '/api/public/virtual-tick'
      preLoaderRoute: typeof ApiPublicVirtualTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-push': {
      id: '/api/public/hooks/send-push'
      path: '/api/public/hooks/send-push'
      fullPath: '/api/public/hooks/send-push'
      preLoaderRoute: typeof ApiPublicHooksSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-scheduled-push': {
      id: '/api/public/hooks/process-scheduled-push'
      path: '/api/public/hooks/process-scheduled-push'
      fullPath: '/api/public/hooks/process-scheduled-push'
      preLoaderRoute: typeof ApiPublicHooksProcessScheduledPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/broadcast-push': {
      id: '/api/public/hooks/broadcast-push'
      path: '/api/public/hooks/broadcast-push'
      fullPath: '/api/public/hooks/broadcast-push'
      preLoaderRoute: typeof ApiPublicHooksBroadcastPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface VirtualRouteChildren {
  VirtualChampionshipRoute: typeof VirtualChampionshipRoute
  VirtualHistoryRoute: typeof VirtualHistoryRoute
  VirtualInstantRoute: typeof VirtualInstantRoute
}

const VirtualRouteChildren: VirtualRouteChildren = {
  VirtualChampionshipRoute: VirtualChampionshipRoute,
  VirtualHistoryRoute: VirtualHistoryRoute,
  VirtualInstantRoute: VirtualInstantRoute,
}

const VirtualRouteWithChildren =
  VirtualRoute._addFileChildren(VirtualRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  ArcadeRoute: ArcadeRoute,
  BetHistoryRoute: BetHistoryRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GangsRoute: GangsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  LotteryRoute: LotteryRoute,
  MatchesRoute: MatchesRouteWithChildren,
  ModRoute: ModRoute,
  NotificationsRoute: NotificationsRoute,
  PollsRoute: PollsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  SurveysRoute: SurveysRoute,
  TasksRoute: TasksRoute,
  TournamentRoute: TournamentRoute,
  TransactionsRoute: TransactionsRoute,
  TriviaRoute: TriviaRoute,
  VirtualRoute: VirtualRouteWithChildren,
  WatchlistRoute: WatchlistRoute,
  WithdrawRoute: WithdrawRoute,
  TicketIdRoute: TicketIdRoute,
  ApiPublicVirtualTickRoute: ApiPublicVirtualTickRoute,
  ApiPublicHooksBroadcastPushRoute: ApiPublicHooksBroadcastPushRoute,
  ApiPublicHooksProcessScheduledPushRoute:
    ApiPublicHooksProcessScheduledPushRoute,
  ApiPublicHooksSendPushRoute: ApiPublicHooksSendPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
